### ISSUE TITLE
socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by KucharczykL** [rpm-software-management/spec-cleaner#290]
spec-cleaner 1.2.1-2.3
openSUSE Tumbleweed 20210329

1. Checkout this package: https://build.suse.de/package/show/home:LKucharczyk:branches:SUSE:SLE-15-SP3:GA/release-notes-sle_hpc
2. Run `spec-cleaner -d release-notes-sle_hpc.spec`
3. The error (see below) is shown.

NOTE: Running with `-m` (`spec-cleaner -dm release-notes-sle_hpc.spec`) does not show an error.

Full error:
```
Traceback (most recent call last):
  File "/usr/bin/spec-cleaner", line 11, in <module>
    load_entry_point('spec-cleaner==1.2.1', 'console_scripts', 'spec-cleaner')()
  File "/usr/lib/python3.8/site-packages/spec_cleaner/__init__.py", line 165, in main
    cleaner.run()
  File "/usr/lib/python3.8/site-packages/spec_cleaner/rpmcleaner.py", line 390, in run
    self.current_section.add(line)
  File "/usr/lib/python3.8/site-packages/spec_cleaner/rpmpreamble.py", line 442, in add
    response = urlopen(https_url, timeout=1)
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib64/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib64/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by kstreitova** [comment]
I believe that this should be fixed by 461da8e296dfc9754bc246e2e4a83e22878f5241
Please reopen it if you bump into it again.
